version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: api_rol_challenge_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - api_rol_challenge

  api_rol_challenge_webserver:
    image: nginx:alpine
    container_name: api_rol_challenge_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - api_rol_challenge

  api_rol_challenge_db:
    image: mysql:8.0
    container_name: api_rol_challenge_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: api_rol_challenge
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - api_rol_challenge

volumes:
  dbdata:

networks:
  api_rol_challenge:
    driver: bridge
